version: "3"

services:
  gobble:
    container_name: gobble
    image: ghcr.io/evanebb/gobble:0.0.6
    build:
      context: ../
      dockerfile: Dockerfile
    depends_on:
      - database
    ports:
      - "80:80/tcp"
    environment:
      GOBBLE_DB_USER: gobble
      GOBBLE_DB_PASS: Welkom123!
      GOBBLE_DB_HOST: database
      GOBBLE_DB_NAME: gobble

  database:
    container_name: gobble_database
    image: postgres:15
    volumes:
      - "db_data:/var/lib/postgresql/data"
      - "./schema.sql:/docker-entrypoint-initdb.d/schema.sql:ro"
    environment:
      POSTGRES_USER: gobble
      POSTGRES_DB: gobble
      POSTGRES_PASSWORD: Welkom123!

volumes:
  db_data: {}
